name: CA trigger

on:
  workflow_run:
    workflows: ["CA"]
    branches: ["main", "develop", "ga"]
    types: ["completed"]

jobs:
  DownloadAndOutput:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: download artifact from latest CD pipeline
        id: down
        run: |
          artifactUrl=$(curl https://api.github.com/repos/OfficeDev/TeamsFx/actions/workflows/22583747/runs | jq '.workflow_runs[0].artifacts_url')
          echo "::set-output name=url::$(curl $artifactUrl|jq '.artifacts[0].archive_download_url')"
        
      - run: |
          echo ${{steps.down.outputs.url}}
      - uses: suisei-cn/actions-download-file@v1
        id: downloadfile  # Remember to give an ID if you need the output filename
        name: Download the file
        with:
          url: ${{steps.down.outputs.url}}
          target: public/

      - run:  |
          ls -a public/