name: CA trigger

on:
  workflow_run:
    workflows: ["CA"]
    branches: ["main", "develop", "ga"]
    types: ["completed"]
  workflow_dispatch:
    inputs:
      url:
        required: true
        default: ""

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{github.event.inputs.url}}
    steps:
      - uses: suisei-cn/actions-download-file@v1
        id: downloadfile  # Remember to give an ID if you need the output filename
        name: Download the file
        with:
          url: ${{github.event.inputs.url}}
          target: public/

      - run:  |
          ls -l public/
  DownloadAndOutput:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: download artifact from latest CD pipeline
        id: down
        run: |
          artifactUrl=$(curl https://api.github.com/repos/wenytang-ms/TestSecrets/actions/workflows/22583747/runs | jq -r '.workflow_runs[0].artifacts_url')
          echo "::set-output name=url::$(curl $artifactUrl|jq -r '.artifacts[0].archive_download_url')"
        
      - run: |
          echo ${{steps.down.outputs.url}}
      - uses: suisei-cn/actions-download-file@v1
        id: downloadfile  # Remember to give an ID if you need the output filename
        name: Download the file
        with:
          url: https://api.github.com/repos/wenytang-ms/TestSecrets/actions/artifacts/249977074
          target: public/

      - run:  |
          ls -l public/