name: CA

on:
  workflow_dispatch:
    inputs:
      update-tag:
        description: "update tag or bump up tag"
        required: true
        default: "false"
jobs:
  ca:
    runs-on: ubuntu-latest
    steps:
      - name: Validate CD branch
        if: ${{ github.event_name == 'workflow_dispatch' && github.ref != 'refs/heads/develop' }}
        run: |
          echo It's not allowed to run CD on other branch except main or develop.
          exit 1
      
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: fetch latest tag
        uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag
      
      - name: output tags
        run: |
          echo ${{steps.get-latest-tag.outputs.tag}} > release.txt
        
      - name: output the tags
        uses: actions/upload-artifact@v3
        with:
          name: release
          path: ./release.txt
          
