name: CA

on:
  workflow_dispatch:
    inputs:
      update-tag:
        description: "update tag or bump up tag"
        required: true
        default: "false"
      pkgs:
        type: string
        required: false
        description: "set pkgs to manage"

jobs:
  ca:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: update pkgs
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.pkgs }}
        run:
          bash .github/scripts/lerna.sh ${{github.event.inputs.pkgs}}
      
      - name: check lerna
        run: |
          cat lerna.json
