name: CA

on:
  workflow_dispatch:
    inputs:
      update-tag:
        description: "update tag or bump up tag"
        required: true
        default: "false"
jobs:
  ca:
    runs-on: ubuntu-latest
    steps:
      - name: Validate CD branch
        if: ${{ github.event_name == 'workflow_dispatch' && github.ref != 'refs/heads/develop' }}
        run: |
          echo It's not allowed to run CD on other branch except main or develop.
          exit 1
      
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14
      
      - name: Setup git
        run: |
          git config --global user.name 'test'
          git config --global user.email 'test@test.com'

      - name: release alpha npm packages to npmjs.org
        run: |
          npx lerna version prerelease --preid=alpha.$(git rev-parse --short HEAD) --exact --no-push --allow-branch ${GITHUB_REF#refs/*/} --yes

      - name: version change
        id: version-change
        run: |
          echo "::set-output name=CHANGED::$(git tag --points-at HEAD | xargs)"
      
      - name: save release info
        if: ${{ steps.version-change.outputs.CHANGED }}
        run: |
          echo ${{steps.version-change.outputs.CHANGED}} > release.txt

      - name: save pkg info
        run: |
          lerna ls --all --json > release.json
      
      - name: output the tags
        if: ${{ steps.version-change.outputs.CHANGED }}
        uses: actions/upload-artifact@v3
        with:
          name: release
          path: |
            release.txt
            release.json
          
