name: CA

on:
  workflow_dispatch:
    inputs:
      update-tag:
        description: "update tag or bump up tag"
        required: true
        default: "false"
      pkgs:
        type: string
        required: false
        description: "set pkgs to manage"

jobs:
  ca:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: update pkgs
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.pkgs }}
        run:
          bash .github/scripts/lerna.sh ${{github.event.inputs.pkgs}}
      
      - name: tag
        uses: ncipollo/release-action@v1.7.3
        with:
          token: ${{ secrets.CD_PAT }}
          tag: 'v1.2.0'
          artifacts: ./lerna.json

      - name: send msg
        run:
          curl -X POST -F 'url=https://github.com/wenytang-ms/TestSecrets/releases/tag/v1.2.0' https://wenytest04dev8e7fb0bot.azurewebsites.net/api/notification
