name: "Lint PR"

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
jobs:
  attension-on-version:
    if: ${{ github.event_name ==  'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - name: echo branch
        run: |
          echo ${GITHUB_REF#refs/*/}
      - name: checkout branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.ref }}
      - name: check feature history
        id: description
        run: | 
          head=$(git describe --first-parent --abbrev=0)
          history_cli=$(git log --pretty=format:"%s %h" $head...HEAD -- packages/alpha)
          history_toolkit=$(git log --pretty=format:"%s %h" $head...HEAD -- packages/beta)
          info=$(echo -e "$history_cli" '\n======================' "$history_toolkit")
          echo "LERNA_STRING.HISTORY<<EOF" >> $GITHUB_ENV
          echo "$info" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Setup node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14
      
      - name: lerna version
        run: |
          git checkout wenyt/tt321
          npx lerna version --conventional-commits --conventional-prerelease --no-git-tag-version --no-push --allow-branch wenyt/tt321 --yes
          echo "LERNA_STRING.INFO<<EOF" >> $GITHUB_ENV
          echo "$(lerna ls --long)" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: output env
        run: |
          echo '============================='
          echo ${{env.LERNA_STRING.INFO}}
          echo '==============================='
          echo ${{env.LERNA_STRING.HISTORY}}
          echo '=================================='
          echo ${{ join(env.LERNA_STRING*, '\n') }}
      
      - uses: riskledger/update-pr-description@v2
        with:
          body: ${{join(env.LERNA_STRING.*, '\n')}}
          token: ${{ secrets.GITHUB_TOKEN }}