name: "Lint PR"

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
jobs:
  attension-on-version:
    if: ${{ github.event_name ==  'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - name: echo branch
        run: |
          echo ${{ github.event.pull_request.head.ref }}
      - name: checkout branch
        uses: actions/checkout@v2
        
      - name: release stable VSCode extension to github
        if: ${{ contains(steps.version-change.outputs.CHANGED, 'ms-teams-vscode-extension@') && github.event_name == 'workflow_dispatch' && github.event.inputs.preid == 'stable' }}
        uses: ncipollo/release-action@v1.7.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v10.20.30
          artifacts: ./packages/**/*.txt
          artifactErrorsFailBuild: true