name: "Lint PR"

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
jobs:
  attension-on-version:
    if: ${{ github.event_name ==  'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: check feature history
        id: description
        run: | 
          echo "1231231231231232"
          echo '9989890arefoeit'
      - name: output
        run:
          echo ${{ steps.description.outputs.description }}
      # - uses: riskledger/update-pr-description@v2
      #   with:
      #     body: ${{ steps.description.outputs.description }}
      #     token: ${{ secrets.GITHUB_TOKEN }}