name: "Lint PR"

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
jobs:
  attension-on-version:
    if: ${{ github.event_name ==  'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.ref }}
      - name: check feature history
        id: description
        run: | 
          head=$(git describe --first-parent --abbrev=0)
          history_cli=$(git log --pretty=format:"%s %h" $head...HEAD -- packages/alpha)
          history_toolkit=$(git log --pretty=format:"%s %h" $head...HEAD -- packages/beta)
          info=$(echo -e "$history_cli" '\n' "$history_toolkit")
          echo "MY_STRING<<EOF" >> $GITHUB_ENV
          echo "$info" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          
      - uses: riskledger/update-pr-description@v2
        with:
          body: ${{ env.MY_STRING  }}
          token: ${{ secrets.GITHUB_TOKEN }}