name: "Lint PR"

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
jobs:
  attension-on-version:
    if: ${{ github.event_name ==  'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.ref }}
      - name: check feature history
        id: description
        run: | 
          head=$(git describe --first-parent --abbrev=0)
          history_cli=$(git log --pretty=format:"%s %h" $head...HEAD -- packages/alpha)
          echo "::set-output name=descrption0::$(echo $head)"
          echo "::set-output name=descrption1::$(echo $history_cli)"
          
      - uses: riskledger/update-pr-description@v2
        with:
          body: ${{join(steps.description.outputs.*, '\n')}}
          token: ${{ secrets.GITHUB_TOKEN }}